# Описание

Код для создания тренировочной и тестовой выборки из основного и дополнительного набора признаков на основании отбора наиболее важных признаков.

В файле kyberpolka_dataset_explore.ipynb проведен предварительный анализ важности признаков на объединенной подвыборке в 5% строк из основных и дополнительных признаков. На  подвыборке обучены RandomForestClassifier и CatboostClassifier и рассчитаны усредненные по всем целевым переменным важности признаков. Отсортированные по важности наборы сохранены в файлах feature_importance_rf.json и feature_importance_cat.json.

Для объединения двух наборов рассчитывается средневзвешенная сумма важностей rf и catboost с весами 0.4 и 0.6 соответственно. 0.6/0.4 — это компромисс, дающий чуть больше веса более точному методу: CatBoost обычно показывает лучшее качество на табличных данных с категориальными признаками. 

Из отсортированного по комбинированной важности списка берётся нужное количество признаков, дающих 90% или 95% важности. Затем эти признаки разделяются на два списка: те, что присутствуют в основном датасете (top_main_features), и те, что в дополнительном (top_extra_features).

Для набора дополнительных признаков используется "ленивая загрузка" с целью экономии памяти. С той же целью производится приведение к Float32 и Int32 вместо Float64 и Int64.

Затем основной и дополнительный наборы объединяются по customer_id (left join) в единую матрицу признаков для обучения. 

Тестовая выборка обрабатывается аналогично.

In [1]:
import gc
import numpy as np
import polars as pl
import json
import pandas as pd

In [2]:
!pip install polars

Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.35.2)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars) (1.35.2)

In [3]:
try:
    import pyarrow
    print("PyArrow is installed. Version:", pyarrow.__version__)
except ModuleNotFoundError:
    print("PyArrow is NOT found in this environment. You installed it in a different one.")

PyArrow is installed. Version: 23.0.1

In [4]:
train = pl.read_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/train_main_features.parquet')
test = pl.read_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/test_main_features.parquet')

In [5]:
test_extra = pl.read_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/test_extra_features.parquet')

In [6]:
feature_importance_rf = pd.read_json('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/feature_importance_rf.json', orient='records')
print("Загружено из JSON:")
print(feature_importance_rf.head())
feature_importance_cat = pd.read_json('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/feature_importance_cat.json', orient='records')
print("Загружено из JSON:")
print(feature_importance_cat.head())

Загружено из JSON:
            feature  importance_rf
0    num_feature_87       0.004691
1    num_feature_62       0.003942
2    num_feature_27       0.003800
3   num_feature_879       0.003702
4  num_feature_1377       0.003294
Загружено из JSON:
            feature  importance_cat
0    num_feature_41        3.462705
1    num_feature_22        1.337958
2  num_feature_1309        1.239737
3  num_feature_1644        1.128667
4    num_feature_42        1.092923

In [7]:
# объединение по имени признака
combined = feature_importance_cat.merge(
    feature_importance_rf, 
    on='feature', 
    suffixes=('_cat', '_rf')
)

# нормализовация
combined['imp_cat_norm'] = combined['importance_cat'] / combined['importance_cat'].max()
combined['imp_rf_norm'] = combined['importance_rf'] / combined['importance_rf'].max()

# комбинированная важность
combined['importance_combined'] = 0.6 * combined['imp_cat_norm'] + 0.4 * combined['imp_rf_norm']

# сортировка и кумулята
combined = combined.sort_values('importance_combined', ascending=False)
combined['cumulative_pct'] = combined['importance_combined'].cumsum() / combined['importance_combined'].sum()

# отбор по порогам
n_90 = (combined['cumulative_pct'] <= 0.9).sum() + 1
n_95 = (combined['cumulative_pct'] <= 0.95).sum() + 1

top_90_features = combined.head(n_90)['feature'].tolist()
top_95_features = combined.head(n_95)['feature'].tolist()

In [8]:
top_main_features = [f for f in top_95_features if f in train.columns]
top_extra_features = [f for f in top_95_features if f in test_extra.columns]

print(f"\nВыбрано признаков: {len(top_95_features)}")
print(f"  Из основного набора: {len(top_main_features)}")
print(f"  Из дополнительного: {len(top_extra_features)}")

Выбрано признаков: 1623
  Из основного набора: 149
  Из дополнительного: 1474

In [9]:
train_main = train[['customer_id'] + top_main_features]
train_main.head()

shape: (5, 150)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ num_featu ┆ num_featu ┆ num_featu ┆ … ┆ num_featu ┆ cat_featu ┆ cat_featu ┆ cat_feat │
│ id        ┆ re_41     ┆ re_87     ┆ re_27     ┆   ┆ re_37     ┆ re_34     ┆ re_30     ┆ ure_61   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1000001   ┆ 0.445712  ┆ null      ┆ -0.020738 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 2.0       ┆ 2.0      │
│ 1000002   ┆ -0.583389 ┆ -0.018017 ┆ -0.004672 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 0.0       ┆ 0.0      │
│ 1000003   ┆ -0.197476 ┆ null      ┆ -0.020788 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 0.0       ┆ 0.0      │
│ 1000004   ┆ null      ┆ null      ┆ null      ┆ … ┆ -0.040013 ┆ 212.0     ┆ 2.0       ┆ 2.0      │
│ 1000005   ┆ -0.004519 ┆ null      ┆ -0.019913 ┆ … ┆ null      ┆ 212.0     ┆ 0.0       ┆ 0.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
test_main = test[['customer_id'] + top_main_features]
test_main.head()

shape: (5, 150)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ num_featu ┆ num_featu ┆ num_featu ┆ … ┆ num_featu ┆ cat_featu ┆ cat_featu ┆ cat_feat │
│ id        ┆ re_41     ┆ re_87     ┆ re_27     ┆   ┆ re_37     ┆ re_34     ┆ re_30     ┆ ure_61   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1750001   ┆ 0.960263  ┆ null      ┆ -0.018283 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 2.0       ┆ 0.0      │
│ 1750002   ┆ -0.712026 ┆ null      ┆ -0.016736 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 2.0       ┆ 0.0      │
│ 1750003   ┆ 1.153219  ┆ null      ┆ -0.020352 ┆ … ┆ null      ┆ 212.0     ┆ 2.0       ┆ 2.0      │
│ 1750004   ┆ 0.381394  ┆ null      ┆ -0.018194 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 2.0       ┆ 2.0      │
│ 1750005   ┆ null      ┆ null      ┆ -0.017956 ┆ … ┆ -0.040013 ┆ 212.0     ┆ 2.0       ┆ 2.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
lazy_extra = pl.scan_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/train_extra_features.parquet')

lazy_extra = lazy_extra.cast(pl.Float64)

lazy_extra = lazy_extra.select(['customer_id'] + top_extra_features)

train_extra = lazy_extra.collect()

In [12]:
train_extra = train_extra.with_columns(
    [pl.col(c).cast(pl.Float32) for c in train_extra.columns if train_extra[c].dtype == pl.Float64]
)
train_extra = train_extra.with_columns(
    pl.col('customer_id').cast(pl.Int32)
)

In [13]:
test_extra = test_extra[['customer_id'] + top_extra_features]

In [14]:
test_extra = test_extra.with_columns(
    [pl.col(c).cast(pl.Float32) for c in train_extra.columns if test_extra[c].dtype == pl.Float64]
)
test_extra = test_extra.with_columns(
    pl.col('customer_id').cast(pl.Int32)
)

In [15]:
train_combined = train_main.join(
    train_extra,
    on='customer_id',
    how='left'  
)

print("Размер после объединения train и extra:", train_combined.height)
print("Количество столбцов:", train_combined.width)

train_combined.write_parquet('train_combined_1600.parquet')

Размер после объединения train и extra: 750000
Количество столбцов: 1624

In [16]:
test_combined = test_main.join(
    test_extra,
    on='customer_id',
    how='left'  
)

print("Размер после объединения test и extra:", test_combined.height)
print("Количество столбцов:", test_combined.width)

test_combined.write_parquet('test_combined_1600.parquet')

Размер после объединения test и extra: 250000
Количество столбцов: 1624