In [1]:
import gc
import numpy as np
import polars as pl
import json
import pandas as pd

In [2]:
!pip install polars

Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.35.2)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars) (1.35.2)

In [3]:
try:
    import pyarrow
    print("PyArrow is installed. Version:", pyarrow.__version__)
except ModuleNotFoundError:
    print("PyArrow is NOT found in this environment. You installed it in a different one.")

PyArrow is installed. Version: 23.0.1

In [4]:
train = pl.read_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/train_main_features.parquet')
test = pl.read_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/test_main_features.parquet')

In [5]:
test_extra = pl.read_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/test_extra_features.parquet')

In [6]:
feature_importance_rf = pd.read_json('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/feature_importance_rf.json', orient='records')
print("Загружено из JSON:")
print(feature_importance_rf.head())
feature_importance_cat = pd.read_json('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/feature_importance_cat.json', orient='records')
print("Загружено из JSON:")
print(feature_importance_cat.head())

Загружено из JSON:
            feature  importance_rf
0    num_feature_87       0.004691
1    num_feature_62       0.003942
2    num_feature_27       0.003800
3   num_feature_879       0.003702
4  num_feature_1377       0.003294
Загружено из JSON:
            feature  importance_cat
0    num_feature_41        3.462705
1    num_feature_22        1.337958
2  num_feature_1309        1.239737
3  num_feature_1644        1.128667
4    num_feature_42        1.092923

In [7]:
# Объединяем важности из двух источников
combined_importance = feature_importance_cat.copy()
combined_importance = combined_importance.rename(columns={'importance': 'importance_cat'})
combined_importance['importance_rf'] = feature_importance_rf['importance_rf']

combined_importance['importance_cat_norm'] = (
    combined_importance['importance_cat'] / combined_importance['importance_cat'].max()
)
combined_importance['importance_rf_norm'] = (
    combined_importance['importance_rf'] / combined_importance['importance_rf'].max()
)

combined_importance['importance_combined'] = (
    combined_importance['importance_cat_norm'] * 0.6 +
    combined_importance['importance_rf_norm'] * 0.4
)

combined_importance = combined_importance.sort_values('importance_combined', ascending=False)
combined_importance['cumulative_importance'] = combined_importance['importance_combined'].cumsum()
combined_importance['cumulative_pct'] = combined_importance['cumulative_importance'] / combined_importance['importance_combined'].sum()

In [8]:
#  Выбираем топ-1600
top_features = feature_importance_cat.head(1600)['feature'].tolist()

In [9]:
top_main_features = [f for f in top_features if f in train.columns]
top_extra_features = [f for f in top_features if f in test_extra.columns]

print(f"\nВыбрано признаков: {len(top_features)}")
print(f"  Из основного набора: {len(top_main_features)}")
print(f"  Из дополнительного: {len(top_extra_features)}")

Выбрано признаков: 1600
  Из основного набора: 149
  Из дополнительного: 1451

In [10]:
train_main = train[['customer_id'] + top_main_features]
train_main.head()

shape: (5, 150)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ num_featu ┆ num_featu ┆ num_featu ┆ … ┆ cat_featu ┆ num_featu ┆ cat_featu ┆ cat_feat │
│ id        ┆ re_41     ┆ re_22     ┆ re_42     ┆   ┆ re_2      ┆ re_78     ┆ re_66     ┆ ure_5    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1000001   ┆ 0.445712  ┆ null      ┆ -0.002153 ┆ … ┆ 0.0       ┆ -0.097437 ┆ 2.0       ┆ 2.0      │
│ 1000002   ┆ -0.583389 ┆ null      ┆ -0.001728 ┆ … ┆ 0.0       ┆ -0.097437 ┆ 0.0       ┆ 0.0      │
│ 1000003   ┆ -0.197476 ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ -0.097437 ┆ 2.0       ┆ 0.0      │
│ 1000004   ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ -0.097437 ┆ 0.0       ┆ 2.0      │
│ 1000005   ┆ -0.004519 ┆ null      ┆ null      ┆ … ┆ 2.0       ┆ -0.097437 ┆ 2.0       ┆ 0.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
test_main = test[['customer_id'] + top_main_features]
test_main.head()

shape: (5, 150)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ num_featu ┆ num_featu ┆ num_featu ┆ … ┆ cat_featu ┆ num_featu ┆ cat_featu ┆ cat_feat │
│ id        ┆ re_41     ┆ re_22     ┆ re_42     ┆   ┆ re_2      ┆ re_78     ┆ re_66     ┆ ure_5    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1750001   ┆ 0.960263  ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ -0.097437 ┆ 0.0       ┆ 2.0      │
│ 1750002   ┆ -0.712026 ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ -0.097437 ┆ 2.0       ┆ 2.0      │
│ 1750003   ┆ 1.153219  ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ null      ┆ 0.0       ┆ 2.0      │
│ 1750004   ┆ 0.381394  ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ -0.097437 ┆ 2.0       ┆ 2.0      │
│ 1750005   ┆ null      ┆ null      ┆ null      ┆ … ┆ 1.0       ┆ -0.097437 ┆ 2.0       ┆ 2.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
lazy_extra = pl.scan_parquet('/kaggle/input/datasets/mashamalyshkina/kyberpolka-dataset/train_extra_features.parquet')

lazy_extra = lazy_extra.cast(pl.Float64)

lazy_extra = lazy_extra.select(['customer_id'] + top_extra_features)

train_extra = lazy_extra.collect()

In [13]:
train_extra = train_extra.with_columns(
    [pl.col(c).cast(pl.Float32) for c in train_extra.columns if train_extra[c].dtype == pl.Float64]
)
train_extra = train_extra.with_columns(
    pl.col('customer_id').cast(pl.Int32)
)

In [14]:
test_extra = test_extra[['customer_id'] + top_extra_features]

In [15]:
test_extra = test_extra.with_columns(
    [pl.col(c).cast(pl.Float32) for c in train_extra.columns if test_extra[c].dtype == pl.Float64]
)
test_extra = test_extra.with_columns(
    pl.col('customer_id').cast(pl.Int32)
)

In [16]:
train_combined = train_main.join(
    train_extra,
    on='customer_id',
    how='left'  
)

print("Размер после объединения train и extra:", train_combined.height)
print("Количество столбцов:", train_combined.width)

train_combined.write_parquet('train_combined_1600.parquet')

Размер после объединения train и extra: 750000
Количество столбцов: 1601

In [17]:
test_combined = test_main.join(
    test_extra,
    on='customer_id',
    how='left'  
)

print("Размер после объединения test и extra:", test_combined.height)
print("Количество столбцов:", test_combined.width)

test_combined.write_parquet('test_combined_1600.parquet')

Размер после объединения test и extra: 250000
Количество столбцов: 1601